library(ape); library(phytools)
x <- read.tree(file = "./tree.newick")
tree <- ape::read.tree(file = "./tree.newick")
tree <- ape::compute.brlen(tree)
tree <- phytools::force.ultrametric(tree, method = "extend")
write.tree(tree, "./tree_brlen.newick")